"""
LLM providers — the pluggable text-generation backend.

The simulation never calls an LLM SDK directly. It talks to a :class:`LLMProvider`,
which exposes a single method. Swap backends (Anthropic API, a local
OpenAI-compatible server, a deterministic mock) without touching engine or
generator code.

Selection rules
---------------
* ``CIVSIM_LLM=mock`` (or unset / no API key) -> :class:`MockProvider`
* ``CIVSIM_LLM=anthropic`` and ``ANTHROPIC_API_KEY`` set -> :class:`AnthropicProvider`
* ``CIVSIM_LLM=openai`` (local server) -> :class:`OpenAICompatibleProvider`

This means you can "run through the flow" with zero setup using the mock, then
point at a real model once you have a key.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol


@dataclass
class GenRequest:
    """A single generation request.

    ``context_docs`` are the structured memory items (state cards, recent
    chronicle entries) the provider should fold into its prompt. Kept as plain
    strings so any backend can format them however it likes.
    """

    system: str
    user: str
    context_docs: list[str]
    max_tokens: int = 1500


class LLMProvider(Protocol):
    """Anything that can turn a :class:`GenRequest` into text."""

    name: str

    def generate(self, req: GenRequest) -> str:  # pragma: no cover - protocol
        ...


# ---------------------------------------------------------------------------
# Mock provider — no API key required, deterministic templates
# ---------------------------------------------------------------------------


class MockProvider:
    """Deterministic fallback that stitches context into a readable template.

    Good enough to exercise the full pipeline (engine -> generator -> archive)
    end-to-end without network or cost. Output is clearly templated so it's
    never mistaken for real LLM prose.
    """

    name = "mock"

    def generate(self, req: GenRequest) -> str:
        ctx = "\n".join(f"- {d}" for d in req.context_docs) or "- (no context)"
        # A light genre hint from the system prompt keeps mocks readable.
        return (
            f"[mock-llm] {req.user.strip()}\n\n"
            f"Context used:\n{ctx}\n\n"
            f"(Generated by MockProvider; set CIVSIM_LLM=anthropic and "
            f"ANTHROPIC_API_KEY for real prose.)"
        )


# ---------------------------------------------------------------------------
# Anthropic provider
# ---------------------------------------------------------------------------


class AnthropicProvider:
    """Calls the Anthropic Messages API (Claude). Requires ANTHROPIC_API_KEY."""

    name = "anthropic"

    def __init__(self, model: str = "claude-sonnet-4-5-20250929", api_key: str | None = None):
        # 默认用 Sonnet 4.5：长叙事一致性 + 成本的平衡点。要更强一致性可换
        # claude-opus 系列；要更省可换 claude-haiku 系列。model 字符串即 API model id。
        # 懒导入 anthropic：这样走 mock 路径时无需安装 anthropic 包。
        from anthropic import Anthropic

        self._client = Anthropic(api_key=api_key or os.environ.get("ANTHROPIC_API_KEY"))
        self.model = model

    def generate(self, req: GenRequest) -> str:
        context_block = ""
        if req.context_docs:
            context_block = "\n\nReference material (use faithfully):\n" + "\n".join(
                f"- {d}" for d in req.context_docs
            )
        msg = self._client.messages.create(
            model=self.model,
            max_tokens=req.max_tokens,
            system=req.system,
            messages=[{"role": "user", "content": req.user + context_block}],
        )
        # message.content is a list of content blocks; concatenate text blocks.
        parts = [b.text for b in msg.content if getattr(b, "type", None) == "text"]
        return "".join(parts).strip()


# ---------------------------------------------------------------------------
# OpenAI-compatible provider (local models: vLLM, Ollama, LM Studio, ...)
# ---------------------------------------------------------------------------


class OpenAICompatibleProvider:
    """Talks to any OpenAI-compatible /v1/chat/completions endpoint.

    Use for local models (Qwen via Ollama/LM Studio, vLLM, etc.). Set
    ``CIVSIM_OPENAI_BASE`` (e.g. http://localhost:11434/v1) and
    ``CIVSIM_OPENAI_MODEL``.
    """

    name = "openai"

    def __init__(
        self,
        base_url: str | None = None,
        model: str | None = None,
        api_key: str | None = None,
    ):
        from openai import OpenAI

        self._client = OpenAI(
            base_url=base_url or os.environ.get("CIVSIM_OPENAI_BASE"),
            api_key=api_key or os.environ.get("CIVSIM_OPENAI_KEY", "not-needed"),
        )
        self.model = model or os.environ.get("CIVSIM_OPENAI_MODEL", "qwen2.5:14b")

    def generate(self, req: GenRequest) -> str:
        context_block = ""
        if req.context_docs:
            context_block = "\n\nReference material (use faithfully):\n" + "\n".join(
                f"- {d}" for d in req.context_docs
            )
        resp = self._client.chat.completions.create(
            model=self.model,
            max_tokens=req.max_tokens,
            messages=[
                {"role": "system", "content": req.system},
                {"role": "user", "content": req.user + context_block},
            ],
        )
        return (resp.choices[0].message.content or "").strip()


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------


def get_provider(choice: str | None = None) -> LLMProvider:
    """按 ``choice`` 或环境变量 ``CIVSIM_LLM`` 返回一个 provider。

    选择优先级：
    - 显式传入 ``choice`` > 环境变量 ``CIVSIM_LLM`` > 默认 ``"mock"``。

    关键设计：当请求的后端「不可用」时（缺 key / 缺包）自动降级到 mock，
    保证模拟永远能跑——开发者不必为跑通流程而先配齐 API key。
    降级会在 stderr 打印原因，避免静默失败。

    Args:
        choice: "mock" | "anthropic" | "openai"。None 时读环境变量。

    Returns:
        实现了 ``generate(GenRequest) -> str`` 的 provider 实例。
    """
    choice = (choice or os.environ.get("CIVSIM_LLM", "mock")).strip().lower()

    # Anthropic：必须同时显式选择且提供 key，否则降级。
    if choice == "anthropic" and os.environ.get("ANTHROPIC_API_KEY"):
        try:
            return AnthropicProvider()
        except Exception as exc:  # 未装 SDK 等
            print(f"[civsim] Anthropic provider unavailable ({exc}); using mock.")
            return MockProvider()

    # OpenAI 兼容（本地模型）：必须显式提供 base_url。
    if choice == "openai" and os.environ.get("CIVSIM_OPENAI_BASE"):
        try:
            return OpenAICompatibleProvider()
        except Exception as exc:
            print(f"[civsim] OpenAI-compatible provider unavailable ({exc}); using mock.")
            return MockProvider()

    # 兜底：mock，零依赖零成本。
    return MockProvider()


# ---------------------------------------------------------------------------
# Config-file based factory（面向最终用户的接入接口）
# ---------------------------------------------------------------------------


def _load_llm_config(config_path: str = "llm.yaml") -> dict:
    """读取 LLM 接入配置文件。文件不存在则返回空 dict（由上层回退到环境变量/mock）。

    用 yaml 而非 JSON：用户要能照着填、加注释，YAML 更友好。
    """
    p = Path(config_path)
    if not p.exists():
        return {}
    import yaml

    data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    # 文件顶层就是 provider 配置；若包了一层 llm:，则取出来兼容两种写法。
    if isinstance(data, dict) and "provider" in data:
        return data
    if isinstance(data, dict) and "llm" in data and isinstance(data["llm"], dict):
        return data["llm"]
    return data if isinstance(data, dict) else {}


def get_provider_from_config(config_path: str = "llm.yaml") -> tuple[LLMProvider, str]:
    """从 ``llm.yaml`` 构建 provider，给最终用户用。

    这是「我们提供给用户的接入接口」：用户编辑一份带注释的 ``llm.yaml`` 即可接上
    自己的模型，无需设环境变量、无需改代码、无需懂 Python。

    配置字段（全部可选；详见 llm.yaml 模板注释）::

        provider: mock | anthropic | openai | local
        model:    模型 id（如 deepseek-chat / qwen2.5:14b / claude-sonnet-4-5-...）
        base_url: OpenAI 兼容端点（openai/local 用；anthropic 不用）
        api_key:  对应平台的 key（mock/local 不用）

    返回顺序：``llm.yaml`` > 环境变量 > mock。
    不可用时（缺 key / 缺包）整洁地降级到 mock 并打印原因，保证游戏永远能开。

    Returns:
        (provider, source_label) —— source_label 供 CLI 展示「用了哪个后端」。
    """
    cfg = _load_llm_config(config_path)
    if not cfg:
        # 没有配置文件：回退到环境变量工厂，行为与原先一致。
        return get_provider(), "env-or-mock"

    provider = (cfg.get("provider") or "").strip().lower()
    model = cfg.get("model")
    base_url = cfg.get("base_url")
    api_key = cfg.get("api_key")

    if provider == "anthropic" and (api_key or os.environ.get("ANTHROPIC_API_KEY")):
        try:
            return AnthropicProvider(model=model or None, api_key=api_key), "anthropic"
        except Exception as exc:
            print(f"[civsim] llm.yaml 指定 anthropic 不可用（{exc}），降级 mock。")
            return MockProvider(), "mock"

    # openai 与 local 同走 OpenAI 兼容实现，区别只在 base_url 是否指向本机。
    if provider in ("openai", "local") and base_url:
        try:
            return (
                OpenAICompatibleProvider(base_url=base_url, model=model, api_key=api_key),
                provider,
            )
        except Exception as exc:
            print(f"[civsim] llm.yaml 指定 {provider} 不可用（{exc}），降级 mock。")
            return MockProvider(), "mock"

    # 兜底：mock。
    return MockProvider(), "mock"
